# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 21:32
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackScratcher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('sizes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2), size=None)),
            ],
        ),
    ]
